# Generated by Django 6.0.3 on 2026-04-02 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descrizione', models.TextField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_ordine', models.DateField()),
                ('stato', models.CharField(choices=[('in_attesa', 'In Attesa'), ('spedito', 'Spedito'), ('consegnato', 'Consegnato'), ('cancellato', 'Cancellato')], default='in_attesa', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini_cliente', to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='OrdineProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField()),
                ('prezzo_unitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dettagli_prodotti', to='core.ordine')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini_prodotto', to='core.prodotto')),
            ],
            options={
                'unique_together': {('ordine', 'prodotto')},
            },
        ),
        migrations.AddField(
            model_name='ordine',
            name='prodotti',
            field=models.ManyToManyField(through='core.OrdineProdotto', to='core.prodotto'),
        ),
    ]
